# Generated by Django 3.1 on 2022-11-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
