# Generated by Django 3.1 on 2022-10-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='score.run'),
        ),
        migrations.AlterField(
            model_name='score',
            name='run',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='score.run'),
        ),
    ]
